### ISSUE TITLE
Python version compatibility with scipy

### ISSUE THREAD

**Issue by KanishAnand** [soraxas/sbp-env#9]
Mentioning the requirement of python `version >= 3.8` in README would also help users the way it's done over [here](https://cs.tinyiu.com/sbp-env/quick-start.html#installation). Python `versions < 3.8` are not compatible with `scipy 1.6`

(Part of the JOSS review openjournals/joss-reviews#3782)

**Comment by soraxas** [comment]
Hi I just tested the repo with virtualenv python 3.7, and I can confirm that python 3.7 should work.

The requirement is mentioned in README in the shield badge:
[![Python version](https://img.shields.io/badge/python-3.7%20%7C%203.8%20%7C%203.9-blue.svg)](https://cs.tinyiu.com/sbp-env)

**Comment by soraxas** [comment]
Specifically I was testing it with `Python 3.7.10`

**Comment by KanishAnand** [comment]
Oh yeah!
I missed that badge. 
Thanks!
